### PR TITLE
Make the fields in Document read-only

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by srawlins** [comment]
Is this a breaking change?

**Comment by kevmoo** [comment]
Strictly speaking, yes!

Although I'm guessing we wouldn't want folks to tweak these...

**Comment by kevmoo** [comment]
@srawlins updated changelog.

Also confirmed that dartdoc and the package site don't use these...

**Comment by srawlins** [comment]
Needs a quick rebase, then LGTM!

**Pull request merged**
