### PR TITLE
Do not allow reference link labels contain left brackets

### PR DESCRIPTION
**Pull request by chenzhiguang**
Fix: https://github.com/dart-lang/markdown/issues/335

### CODE REVIEW

**Comment by srawlins** [comment]
Does this fix a Commonmark spec then? Can you run `tool/stats.dart --update-files` and `tool/stats.dart --update-files --flavor=gfm` to update the compliance stat files?

**Comment by chenzhiguang** [comment]
> Does this fix a Commonmark spec then? Can you run `tool/stats.dart --update-files` and `tool/stats.dart --update-files --flavor=gfm` to update the compliance stat files?

I have updated the stat files by running `stats.dart`

**Comment by srawlins** [comment]
We should not change the unit files case-by-case, they are meant to be an exact set of test cases from a single version of the commonmark specs. I'll look into bumping them.

**Comment by srawlins** [comment]
Sorry, I totally mis-remembered how we maintain the spec tests. @kevmoo can maybe confirm:

`tool/stats.dart --update-files` will use `tool/common_mark_tests.json` to run specs, and update all of the unit files in `test/`.

Then the unit files represent what the markdown package currently outputs, so that a clean checkout will always have 100% tests passing.

`tool/common_mark_tests.json` is updated separately (download?), e.g. in [#383](https://github.com/dart-lang/markdown/pull/383/files#diff-ad9d1f3e38cc0928c5c6881aaf8edc900b1abadd673e56e6f9a37033add31b1e).

When someone improves compliance (like this PR), the unit file changes, and `tool/*_stats.json` and `tool/*_stats.txt` are updated (via `tool/stats.dart --update-files`).

**Comment by kevmoo** [comment]
I'd have to re-learn, too – even though I wrote it! That sounds right, @srawlins

**Comment by kevmoo** [comment]
So this change seems to make things less broken – but it's still broken.

```
<p>[foo][ref[]</p>
<p>[ref[]: /uri</p>
```

According to spec, this is what we *should* see.

**Review by srawlins — APPROVED** [review]
I'll take the PR because it is strictly better than what we have today 😁. To pass commonmark 545, we just need to also change parsing of the link reference (in addition to the reference link, which you solved).

Thanks!

**Pull request merged**
