### PR TITLE
Bump to 2.1.6

### PR DESCRIPTION
**Pull request by srawlins**

### CODE REVIEW

**Comment by srawlins** [comment]
Hi @natebosch @jakemac53 It's been requested that we cut a markdown release. All of my standard reviewers are OOO; would one of you mind reviewing? (Or is there a good standard packages team to ping?)

**Comment by natebosch** [comment]
> Or is there a good standard packages team to ping?

For better or worse the closest we have to that is to ping me...

**Comment by srawlins** [comment]
I can do it. Thanks for the doc!

**Comment by srawlins** [comment]
The latest markdown commits have landed internally. This is ready for review.

**Pull request merged**
