### PR TITLE
Enable code highlighting in example

### PR DESCRIPTION
**Pull request by kevmoo**
Thoughts?

### CODE REVIEW

**Comment by kevmoo** [comment]
@srawlins Maybe we should add a check-box at the bottom so folks opt-in to this?

...just thinkin'

**Comment by srawlins** [comment]
Can the CSS and highlighting JS files not be referenced from static/CDN servers? https://highlightjs.org/usage/

**Comment by kevmoo** [comment]
@srawlins Yup. Fixed 😄

**Comment by kevmoo** [comment]
@srawlins Thoughts?

**Comment by srawlins** [comment]
Nice! I love it. lgtm.

**Pull request merged**
