### PR TITLE
Add line endings before HTML blocks when they are preceded by blocks.

### PR DESCRIPTION
**Pull request by chenzhiguang**
Now it is 100% GFM!

### Before 
Screenshot 2023-01-30 at 17 52 05

### After
Screenshot 2023-01-30 at 17 50 38

### CODE REVIEW

**Comment by kevmoo** [comment]
How's performance?

**Comment by chenzhiguang** [comment]
Performance has no change. I have just added the benchmarks in the description.

**Comment by kevmoo** [comment]
Ready for you @srawlins – then we can publish?

**Review by srawlins — APPROVED** [review]
Great work, simple solution! Thanks!

**Comment by chenzhiguang** [comment]
Awesome!

**Pull request merged**
